# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1')),
                ('username', models.CharField(max_length=20, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('password', models.CharField(max_length=20, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('level', models.IntegerField(verbose_name=b'\xe7\xad\x89\xe7\xba\xa7')),
            ],
        ),
    ]
