# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectDis',
            fields=[
                ('dayto3', models.IntegerField(default=0)),
                ('dayto10', models.IntegerField(default=0)),
                ('dayto20', models.IntegerField(default=0)),
                ('dayto30', models.IntegerField(default=0)),
                ('dayto60', models.IntegerField(default=0)),
                ('dayto90', models.IntegerField(default=0)),
                ('dayover90', models.IntegerField(default=0)),
                ('currentNum', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='CollectNum',
            fields=[
                ('newAdd', models.IntegerField(default=0)),
                ('newCollectMl1', models.IntegerField(default=0)),
                ('newCollectMu1', models.IntegerField(default=0)),
                ('threeDayCollect', models.IntegerField(default=0)),
                ('threeDayCollectRate', models.FloatField(default=0.0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='CollectRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default=b'2017-04', max_length=128)),
                ('day4Rate', models.FloatField(default=0.0)),
                ('day7Rate', models.FloatField(default=0.0)),
                ('day15Rate', models.FloatField(default=0.0)),
                ('day30Rate', models.FloatField(default=0.0)),
                ('day60Rate', models.FloatField(default=0.0)),
                ('day90Rate', models.FloatField(default=0.0)),
                ('day90Ratem', models.FloatField(default=0.0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='FlowDelayRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundName', models.CharField(default=b'credan', max_length=128)),
                ('delayRate0', models.FloatField(default=0.0)),
                ('delayRate3', models.FloatField(default=0.0)),
                ('delayRate7', models.FloatField(default=0.0)),
                ('delayRate10', models.FloatField(default=0.0)),
                ('delayRate20', models.FloatField(default=0.0)),
                ('delayRateM1', models.FloatField(default=0.0)),
                ('delayRateM2', models.FloatField(default=0.0)),
                ('delayRateM3', models.FloatField(default=0.0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='FlowDelayRateNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundName', models.CharField(default=b'credan', max_length=128)),
                ('newDelayRate3', models.FloatField(default=0.0)),
                ('newRepaySum', models.IntegerField(default=0)),
                ('newPaySum', models.IntegerField(default=0)),
                ('newPaid', models.IntegerField(default=0)),
                ('oldDelayRate3', models.FloatField(default=0.0)),
                ('oldRepaySum', models.IntegerField(default=0)),
                ('oldPaySum', models.IntegerField(default=0)),
                ('oldPaid', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='FlowLoanMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default=b'flash', max_length=32)),
                ('money', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='FlowLoanMoneyNO',
            fields=[
                ('loanOld', models.IntegerField(default=0)),
                ('loanNew', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='FlowLoanMoneySum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default=b'flash', max_length=32)),
                ('money', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='IndexAcrepay',
            fields=[
                ('allRepayMoney', models.IntegerField(default=0)),
                ('acRepayMoney', models.IntegerField(default=0)),
                ('repayRate', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='IndexCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(default=b'china', max_length=32)),
                ('numInCity', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='IndexDash',
            fields=[
                ('avgTermNum', models.IntegerField(default=0)),
                ('avgMoney', models.IntegerField(default=0)),
                ('avgServiceMoney', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='IndexHead',
            fields=[
                ('tradeMoney', models.IntegerField(default=0)),
                ('tradeNum', models.IntegerField(default=0)),
                ('activeUser', models.IntegerField(default=0)),
                ('sumUser', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='IndexHopper',
            fields=[
                ('register', models.IntegerField(default=0)),
                ('applys', models.IntegerField(default=0)),
                ('passs', models.IntegerField(default=0)),
                ('loan', models.IntegerField(default=0)),
                ('reloan', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='MarketNum',
            fields=[
                ('applyPass', models.IntegerField(default=0)),
                ('firstDayT', models.IntegerField(default=0)),
                ('firstDay', models.IntegerField(default=0)),
                ('firstDayRate', models.FloatField(default=0.0)),
                ('tryRate', models.IntegerField(default=0)),
                ('secondDay', models.IntegerField(default=0)),
                ('secondDayRate', models.FloatField(default=0.0)),
                ('thirdDay', models.IntegerField(default=0)),
                ('thirdDayRate', models.FloatField(default=0.0)),
                ('paidNum', models.IntegerField(default=0)),
                ('paidRate', models.FloatField(default=0.0)),
                ('auditTime', models.IntegerField(default=0)),
                ('auditTimeWit', models.IntegerField(default=0)),
                ('auditTimeToday', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='UserAge',
            fields=[
                ('age1', models.IntegerField(default=0)),
                ('age2', models.IntegerField(default=0)),
                ('age3', models.IntegerField(default=0)),
                ('age4', models.IntegerField(default=0)),
                ('age5', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='UserAgeAll',
            fields=[
                ('age1', models.IntegerField(default=0)),
                ('age2', models.IntegerField(default=0)),
                ('age3', models.IntegerField(default=0)),
                ('age4', models.IntegerField(default=0)),
                ('age5', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='UserSex',
            fields=[
                ('male', models.IntegerField(default=0)),
                ('demale', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='UserSexAll',
            fields=[
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
    ]
