# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dayAddApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIncrease',
            fields=[
                ('register', models.IntegerField(default=0)),
                ('allow', models.IntegerField(default=0)),
                ('newApply', models.IntegerField(default=0)),
                ('oldApply', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.RemoveField(
            model_name='usersex',
            name='demale',
        ),
        migrations.AddField(
            model_name='usersex',
            name='female',
            field=models.IntegerField(default=0),
        ),
    ]
