# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dayAddApi', '0002_auto_20171113_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AeyeDelayRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delayRate0', models.FloatField(default=0.0)),
                ('delayRate3', models.FloatField(default=0.0)),
                ('delayRate7', models.FloatField(default=0.0)),
                ('delayRate10', models.FloatField(default=0.0)),
                ('delayRate20', models.FloatField(default=0.0)),
                ('delayRateM1', models.FloatField(default=0.0)),
                ('delayRateM2', models.FloatField(default=0.0)),
                ('delayRateM3', models.FloatField(default=0.0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='AeyeDelayRateNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newDelayRate3', models.FloatField(default=0.0)),
                ('newRepaySum', models.IntegerField(default=0)),
                ('newPaySum', models.IntegerField(default=0)),
                ('newPaid', models.IntegerField(default=0)),
                ('oldDelayRate3', models.FloatField(default=0.0)),
                ('oldRepaySum', models.IntegerField(default=0)),
                ('oldPaySum', models.IntegerField(default=0)),
                ('oldPaid', models.IntegerField(default=0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='AeyeGetRate',
            fields=[
                ('tryNum', models.IntegerField(default=0)),
                ('sucNum', models.IntegerField(default=0)),
                ('sucRate', models.FloatField(default=0.0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
        migrations.CreateModel(
            name='AeyePassRate',
            fields=[
                ('applyNum', models.IntegerField(default=0)),
                ('passNum', models.IntegerField(default=0)),
                ('passRate', models.FloatField(default=0.0)),
                ('createDate', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
    ]
