# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dayAddApi', '0003_aeyedelayrate_aeyedelayrateno_aeyegetrate_aeyepassrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeyedelayrate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='aeyedelayrateno',
            name='id',
        ),
        migrations.AlterField(
            model_name='aeyedelayrate',
            name='createDate',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aeyedelayrateno',
            name='createDate',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
