# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayAddApi', '0004_auto_20171115_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowdelayrateno',
            name='newPaySum',
        ),
        migrations.RemoveField(
            model_name='flowdelayrateno',
            name='oldPaySum',
        ),
    ]
