# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayAddApi', '0005_auto_20171121_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeyedelayrateno',
            name='newPaySum',
        ),
        migrations.RemoveField(
            model_name='aeyedelayrateno',
            name='oldPaySum',
        ),
    ]
