# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dayAddApi', '0006_auto_20171121_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowLoanFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundName', models.CharField(default=b'credan', max_length=128)),
                ('sumMoney', models.FloatField(default=0.0)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('createDate',),
            },
        ),
    ]
